spring:
  datasource: #配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/walk_bookstore?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    #配置druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接池大小
      initial-size: 10
      #最大连接数
      max-active: 100
      #最小连接数
      min-idle: 10
      #连接超时等待时间
      max-wait: 60001
      #是否开启PSCache[某个缓存处理]
      pool-prepared-statements: false
      #配置间隔多久进行一次检查是否有需要关闭的链接
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中存在最小存在时间
      min-evictable-idle-time-millis: 300000
      #配置一些扩展插件[监控统计、防SQL注入、日志]
      filter: stat,wall,log4j2
  cache:
    type: REDIS  #选择处理缓存的工具
  redis:
    host: 127.0.0.1
    port: 6379 #默认是这个端口号
    #password: 没有设置密码不需要配置这个
    database: 8 #使用几号redis库
    timeout: 600 #连接池最大的连接数，若使用负值表示没有限制
    lettuce:
      pool:
        max-active: 50 #连接池最大数
        max-wait: -1 #连接池最大阻塞等待时间，若使用负值表示没有限制
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  mail:
    username: 869819435@qq.com
    password: kathgcjopvzdbdfe  # 授权码
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true


#logging: #设置日志
#  level:  #打印等级
#    root: info

my:
  log:
    path: E:/myspringboot

mybatis:
  #mapper.xml所在位置
  mapperLocations: classpath:mybatis/mapper/**/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true  #大小写驼峰转换
    call-setters-on-nulls: true #设置查询结果为null的时候是否返回
    jdbcTypeForNull: VARCHAR #当没有指定传入参数的时候默认为varchar

pagehelper:
  helper-dialect: mysql #数据库类型[数据库分页原理不同，mysql是limit,sql server是top]
  reasonable: true #分页合理化
  support-methods-arguments: true #是否支持接口参数来传递分页参数，默认false
  page-size-zero: true #当设置为true的时候，如果pageSize设置为0(或RowBounds的limit=0,就不执行分页)


